site_name: Cloudrail Knowledge
repo_url: https://github.com/indeni/cloudrail-knowledge/
repo_name: cloudrail-knowledge
edit_uri: null

nav:
  - Home: 'README.md'
  - Context:
    - 'Cloudrail''s Context Model': 'context/README.md'
    - 'AWS Context':
      - 'account': 'context/aws/account/README.md'
      - 'apigateway': 'context/aws/apigateway/README.md'
      - 'apigatewayv2': 'context/aws/apigatewayv2/README.md'
      - 'athena': 'context/aws/athena/README.md'
      - 'autoscaling': 'context/aws/autoscaling/README.md'
      - 'batch': 'context/aws/batch/README.md'
      - 'cloudfront': 'context/aws/cloudfront/README.md'
      - 'cloudhsmv2': 'context/aws/cloudhsmv2/README.md'
      - 'cloudtrail': 'context/aws/cloudtrail/README.md'
      - 'cloudwatch': 'context/aws/cloudwatch/README.md'
      - 'codebuild': 'context/aws/codebuild/README.md'
      - 'dax': 'context/aws/dax/README.md'
      - 'dms': 'context/aws/dms/README.md'
      - 'docdb': 'context/aws/docdb/README.md'
      - 'ds': 'context/aws/ds/README.md'
      - 'dynamodb': 'context/aws/dynamodb/README.md'
      - 'ec2': 'context/aws/ec2/README.md'
      - 'ecr': 'context/aws/ecr/README.md'
      - 'ecs': 'context/aws/ecs/README.md'
      - 'efs': 'context/aws/efs/README.md'
      - 'eks': 'context/aws/eks/README.md'
      - 'elasticache': 'context/aws/elasticache/README.md'
      - 'elb': 'context/aws/elb/README.md'
      - 'emr': 'context/aws/emr/README.md'
      - 'es': 'context/aws/es/README.md'
      - 'glacier': 'context/aws/glacier/README.md'
      - 'globalaccelerator': 'context/aws/globalaccelerator/README.md'
      - 'glue': 'context/aws/glue/README.md'
      - 'iam': 'context/aws/iam/README.md'
      - 'kinesis': 'context/aws/kinesis/README.md'
      - 'kms': 'context/aws/kms/README.md'
      - 'lambda_': 'context/aws/lambda_/README.md'
      - 'mq': 'context/aws/mq/README.md'
      - 'neptune': 'context/aws/neptune/README.md'
      - 'networking_config': 'context/aws/networking_config/README.md'
      - 'rds': 'context/aws/rds/README.md'
      - 'redshift': 'context/aws/redshift/README.md'
      - 'resourcegroupstaggingapi': 'context/aws/resourcegroupstaggingapi/README.md'
      - 's3': 'context/aws/s3/README.md'
      - 's3outposts': 'context/aws/s3outposts/README.md'
      - 'sagemaker': 'context/aws/sagemaker/README.md'
      - 'secretsmanager': 'context/aws/secretsmanager/README.md'
      - 'sns': 'context/aws/sns/README.md'
      - 'sqs': 'context/aws/sqs/README.md'
      - 'ssm': 'context/aws/ssm/README.md'
      - 'worklink': 'context/aws/worklink/README.md'
      - 'workspaces': 'context/aws/workspaces/README.md'
      - 'xray': 'context/aws/xray/README.md'
    - 'Azure Context':
      - 'databases': 'context/azure/databases/README.md'
      - 'network': 'context/azure/network/README.md'
      - 'webapp': 'context/azure/webapp/README.md'
  - Rules:
    - 'How Rules Work': 'rules/README.md'
    - 'Rules'' Evidence Field': 'rules/evidence.md'
    - 'What is considered a "Context Aware Rule"?': 'rules/context-aware.md'
    - 'Tutorial - Writing Your Own Rule': 'rules/tutorial/README.md'

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
        selection:
          filters:
            - "!^_"
    watch:
      - cloudrail

theme:
  name: material
  logo: assets/cloudrail_small_logo.svg
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true

copyright: 'indeni'
repo_url: 'https://github.com/indeni/cloudrail-knowledge/'
repo_name: 'cloudrail-knowledge'
edit_uri: 'docs/'
